-- MySQL Script generated by MySQL Workbench
-- Thu Jan 25 02:38:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stockmarket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stockmarket` ;

-- -----------------------------------------------------
-- Schema stockmarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stockmarket` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `stockmarket` ;

-- -----------------------------------------------------
-- Table `Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Company` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(500) NOT NULL,
  `sharesRegistered` INT NOT NULL,
  `sharesIssued` INT NOT NULL,
  `sharePrice` DECIMAL(11,2) NULL,
  `marketLicenceNo` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `emailid` VARCHAR(200) NULL,
  `hqAddress` VARCHAR(200) NULL,
  `accountUserID` VARCHAR(100) NULL,
  `accountPassword` VARCHAR(100) NULL,
  `membershipActive` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trader` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trader` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(200) NULL,
  `phone` VARCHAR(15) NULL,
  `address` VARCHAR(200) NULL,
  `emailId` VARCHAR(200) NULL,
  `govtIdNo` VARCHAR(45) NULL,
  `accountUserId` VARCHAR(100) NULL,
  `accountPassword` VARCHAR(100) NULL,
  `membershipActive` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Security_Types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Security_Types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Security_Types` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(200) NULL,
  `votingRights` TINYINT NULL,
  `transferrable` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Transaction_Party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction_Party` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Transaction_Party` (
  `id` VARCHAR(50) NOT NULL,
  `companyId` VARCHAR(50) NULL,
  `traderId` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `companyId_idx` (`companyId` ASC),
  INDEX `traderId_idx` (`traderId` ASC),
  CONSTRAINT `transPartyCompanyFK`
    FOREIGN KEY (`companyId`)
    REFERENCES `Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transPartyTraderFK`
    FOREIGN KEY (`traderId`)
    REFERENCES `Trader` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Securities_List`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Securities_List` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Securities_List` (
  `id` VARCHAR(50) NOT NULL,
  `issued` TINYINT NULL,
  `companyId` VARCHAR(50) NULL,
  `ownerId` VARCHAR(50) NULL,
  `lastSellPrice` DECIMAL(11,2) NULL,
  `currentPrice` DECIMAL(11,2) NULL,
  `securityType` VARCHAR(50) NULL,
  `ownershipStatus` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `copmanyId_idx` (`companyId` ASC),
  INDEX `securityType_idx` (`securityType` ASC),
  INDEX `ownerId_idx` (`ownerId` ASC),
  CONSTRAINT `securtiesCompanyFK`
    FOREIGN KEY (`companyId`)
    REFERENCES `Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `securitiesOwnerFK`
    FOREIGN KEY (`ownerId`)
    REFERENCES `Transaction_Party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `securitiesSecurityTypeFK`
    FOREIGN KEY (`securityType`)
    REFERENCES `Security_Types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Transaction` (
  `id` VARCHAR(50) NOT NULL,
  `securityId` VARCHAR(50) NULL,
  `buyerId` VARCHAR(50) NULL,
  `sellerId` VARCHAR(50) NULL,
  `price` DECIMAL(11,2) NULL,
  `dateAndTime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `securityId_idx` (`securityId` ASC),
  INDEX `transBuyerFK_idx` (`buyerId` ASC),
  INDEX `transSellerFK_idx` (`sellerId` ASC),
  CONSTRAINT `transSecurityFK`
    FOREIGN KEY (`securityId`)
    REFERENCES `Securities_List` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transBuyerFK`
    FOREIGN KEY (`buyerId`)
    REFERENCES `Transaction_Party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transSellerFK`
    FOREIGN KEY (`sellerId`)
    REFERENCES `Transaction_Party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Company_Portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company_Portfolio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Company_Portfolio` (
  `securityId` VARCHAR(50) NOT NULL,
  `purchaseValue` DECIMAL(11,2) NOT NULL,
  `saleValue` DECIMAL(11,2) NULL,
  `currentlyOwned` TINYINT NOT NULL,
  INDEX `securityId_idx` (`securityId` ASC),
  CONSTRAINT `portfolioSecurityIdFK`
    FOREIGN KEY (`securityId`)
    REFERENCES `Securities_List` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trader_Portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trader_Portfolio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trader_Portfolio` (
  `securityId` VARCHAR(50) NOT NULL,
  `purchaseValue` DECIMAL(11,2) NOT NULL,
  `saleValue` DECIMAL(11,2) NULL,
  `currentlyOwned` TINYINT NOT NULL,
  INDEX `securityId_idx` (`securityId` ASC),
  CONSTRAINT `portfolioSecurityIdFK0`
    FOREIGN KEY (`securityId`)
    REFERENCES `Securities_List` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Security_Trend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Security_Trend` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Security_Trend` (
  `companyId` VARCHAR(50) NOT NULL,
  `securityType` VARCHAR(45) NOT NULL,
  `closingPriceAtDate` DECIMAL(11,2) NULL,
  `priceAtMinute` DECIMAL(11,2) NULL,
  PRIMARY KEY (`companyId`, `securityType`),
  INDEX `trendSecurityTypeFK_idx` (`securityType` ASC),
  CONSTRAINT `trendCompanyFK`
    FOREIGN KEY (`companyId`)
    REFERENCES `Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `trendSecurityTypeFK`
    FOREIGN KEY (`securityType`)
    REFERENCES `Security_Types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
