-- MySQL Script generated by MySQL Workbench
-- Mon Feb  5 03:36:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stockmarket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stockmarket` ;

-- -----------------------------------------------------
-- Schema stockmarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stockmarket` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `stockmarket` ;

-- -----------------------------------------------------
-- Table `Trader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trader` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trader` (
  `id` VARCHAR(50) NOT NULL,
  `title` VARCHAR(5) NULL,
  `f_name` VARCHAR(100) NULL,
  `m_name` VARCHAR(100) NULL,
  `l_name` VARCHAR(100) NULL,
  `gender` CHAR NULL,
  `id_proof` VARCHAR(100) NULL,
  `dob` DATE NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(200) NULL,
  `address` VARCHAR(500) NULL,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Company` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(200) NULL,
  `licence` VARCHAR(100) NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(200) NULL,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Security_Types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Security_Types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Security_Types` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NULL,
  `description` VARCHAR(500) NULL,
  `voting_rights` TINYINT NULL,
  `transferrable` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Securities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Securities` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Securities` (
  `id` VARCHAR(50) NOT NULL,
  `company_id` VARCHAR(50) NULL,
  `type_id` VARCHAR(50) NULL,
  `price` DECIMAL(11,2) NULL,
  `registered` INT NULL,
  `issued` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `companyFK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
  -- CONSTRAINT `typeFK`
  --  FOREIGN KEY (`type_id`)
  --  REFERENCES `Security_Types` (`id`)
  --  ON DELETE CASCADE
  --  ON UPDATE CASCADE
  )
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `companyFK_idx` ON `Securities` (`company_id` ASC);

SHOW WARNINGS;

-- SHOW WARNINGS;
-- CREATE INDEX `typeFK_idx` ON `Securities` (`type_id` ASC);
-- -----------------------------------------------------
-- Table `Security_Trend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Security_Trend` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Security_Trend` (
  `security_id` VARCHAR(50) NOT NULL,
  `closing_datetime` DATETIME NULL,
  `closing_price` DECIMAL(11,2) NULL,
  PRIMARY KEY (`security_id`),
  CONSTRAINT `securityFK`
    FOREIGN KEY (`security_id`)
    REFERENCES `Securities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Transaction_Party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction_Party` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Transaction_Party` (
  `id` VARCHAR(50) NOT NULL,
  `company_id` VARCHAR(50) NULL,
  `trader_id` VARCHAR(50) NULL,
  `balance` DECIMAL(11,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Transaction` (
  `id` VARCHAR(50) NOT NULL,
  `buyer_id` VARCHAR(50) NULL,
  `seller_id` VARCHAR(50) NULL,
  `security_id` VARCHAR(50) NULL,
  `number` VARCHAR(50) NULL,
  `amount` DECIMAL(11,2) NULL,
  `t_datetime` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `transBuyerFK1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `Transaction_Party` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transSellerFK1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `Transaction_Party` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `securityFK1`
    FOREIGN KEY (`security_id`)
    REFERENCES `Securities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `transBuyerFK1_idx` ON `Transaction` (`buyer_id` ASC);

SHOW WARNINGS;
CREATE INDEX `transSellerFK1_idx` ON `Transaction` (`seller_id` ASC);

SHOW WARNINGS;
CREATE INDEX `securityFK1_idx` ON `Transaction` (`security_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
